title: CakePHP Brasil
email: https://telegram.me/cakephpbr
description: "CakePHP Brasil é uma comunidade de desenvolvedores apaixonados pelo framework PHP de desenvolvimento rápido."
url: "http://cakephpbrasil.com.br"
header-img: assets/img/home-bg.jpg
baseurl: ""
github_username:  CakePHPBrasil
email_username:  contato@cakephpbrasil.com.br
highlighter: rouge
permalink: pretty
paginate: 10
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
